version: '3.7'
networks:
  default: 
    name: memorizer
services:
  percona:
    build: ../percona
    container_name: percona
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-adminpass}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-memorizer}
    volumes:
      - ${ROOT_DIR}/system/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  be:
    image: be
    container_name: be
    restart: always
    command: sh -c "npm run migration:db && npm run nodemon"
    depends_on:
      - percona
    environment:
      - MAIN_URL=${MAIN_URL:-http://localhost:8000}
      - PORT=${BE_PORT:-8000}
      - IMAGES_PATH=${IMAGES_PATH:-images/}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_ACCESS_KEY_ID=${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
      - MINIO_BUCKET=${MINIO_BUCKET:-object-storage}
      - STATIC_URL=${STATIC_URL:-http://localhost:9000}
      - DB_NAME=${MYSQL_DATABASE:-memorizer}
      - DB_USERNAME=${MYSQL_USER:-admin}
      - DB_PASSWORD=${MYSQL_PASSWORD:-adminpass}
      - DB_HOST=${MYSQL_HOST:-percona}
    volumes:
      - ${ROOT_DIR}/../be:/app
  minio:
    build: ../minio
    container_name: minio
    restart: always
    command: server /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
    volumes:
      - ${ROOT_DIR}/system/minio:/data
  minio-client:
    build: ../minio-client
    container_name: minio-client
    environment:
      - MINIO_HOST=${MINIO_HOST:-minio}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
    entrypoint: sh
    depends_on:
      - minio
    command: /opt/minio.init
  nginx:
    build: ../nginx
    container_name: nginx
    restart: always
    environment:
      TZ: ${TIMEZONE:-Europe/Kiev}
      MODE: ${NGINX_MODE:-default}
    volumes:
      - ${ROOT_DIR}/system/certbot/conf:/etc/letsencrypt
      - ${ROOT_DIR}/system/certbot/www:/var/www/certbot
    ports:
      - 80:80
  ui:
    build: ../ui
    container_name: ui
    restart: always
    

