version: '3.7'
networks:
  default: 
    name: memorizer
services:
  percona:
    build: ../percona
    container_name: percona
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-adminpass}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-memorizer}
    volumes:
      - ${ROOT_DIR}/system/mysql:/var/lib/mysql
  be:
    build: ../be
    container_name: be
    restart: always
    command: sh -c "npm run migration:db && npm start"
    depends_on:
      - percona
    environment:
      - MAIN_URL=${MAIN_URL:-http://localhost:8000}
      - PORT=${BE_PORT:-8000}
      - IMAGES_PATH=${IMAGES_PATH:-images/}
      - S3_ENDPOINT=${MINIO_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY_ID=${MINIO_ACCESS_KEY:-AKIAIOSFODNN7EXAMPLE}
      - S3_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
      - S3_BUCKET=${MINIO_BUCKET:-object-storage}
      - STATIC_URL=${STATIC_URL:-http://localhost:9000}
      - DB_NAME=${MYSQL_DATABASE:-memorizer}
      - DB_USERNAME=${MYSQL_USER:-admin}
      - DB_PASSWORD=${MYSQL_PASSWORD:-adminpass}
      - DB_HOST=${MYSQL_HOST:-percona}
  minio:
    build: ../minio
    container_name: minio
    restart: always
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
    volumes:
      - ${ROOT_DIR}/system/minio:/data
  minio-client:
    build: ../minio-client
    container_name: minio-client
    environment:
      - MINIO_HOST=${MINIO_HOST:-minio}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
    entrypoint: sh
    depends_on:
      - minio
    command: /opt/minio.init
  nginx:
    build: ../nginx
    container_name: nginx
    restart: always
    environment:
      TZ: ${TIMEZONE:-Europe/Kiev}
      MODE: ${NGINX_MODE:-default}
    volumes:
      - ${ROOT_DIR}/system/certbot/conf:/etc/letsencrypt
      - ${ROOT_DIR}/system/certbot/www:/var/www/certbot
    ports:
      - 80:80
      # - 443:443
  ui:
    build: ../ui
    container_name: ui
    restart: always
  # certbot:
  #   image: certbot/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   container_name: certbot
  #   volumes:
  #     - ${ROOT_DIR}/system/certbot/conf:/etc/letsencrypt
  #     - ${ROOT_DIR}/system/certbot/www:/var/www/certbot
    

